name: Deploy to GitHub Pages

on:
  push:
    branches: [ thausif, main ] 
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'Frontend/package-lock.json'

      - name: Install dependencies
        working-directory: ./Frontend
        run: npm ci

      - name: Build
        working-directory: ./Frontend
        run: npm run build -- --configuration production --base-href=/AdvSoftTech-Assignment/

      # Debug step to find build output directory
      - name: List build output directories
        run: |
          echo "Listing build output directories:"
          find Frontend/dist -type d | sort
          echo "Listing HTML files:"
          find Frontend/dist -name "*.html" | sort

      # Dynamically find the correct build output directory
      - name: Find build directory and prepare for deployment
        id: find-build-dir
        run: |
          BUILD_DIR=$(find Frontend/dist -type d -maxdepth 1 | head -n 2 | tail -n 1)
          echo "Found build directory: $BUILD_DIR"
          echo "build_dir=$BUILD_DIR" >> $GITHUB_OUTPUT
          
          # Check if index.html exists
          if [ -f "$BUILD_DIR/index.html" ]; then
            echo "Found index.html, creating 404.html"
            cp "$BUILD_DIR/index.html" "$BUILD_DIR/404.html"
          else
            echo "WARNING: index.html not found in $BUILD_DIR"
            find Frontend/dist -name "index.html"
          fi
          
          # Create .nojekyll file
          touch "$BUILD_DIR/.nojekyll"
          echo "Created .nojekyll file"

      # Deploy using the dynamically found directory
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ steps.find-build-dir.outputs.build_dir }}
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true